language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t fran902/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true fran902/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-814465906134"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"